/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RsButton2 {
    'activateRipple': () => Promise<void>;
  }
}

declare global {


  interface HTMLRsButton2Element extends Components.RsButton2, HTMLStencilElement {}
  var HTMLRsButton2Element: {
    prototype: HTMLRsButton2Element;
    new (): HTMLRsButton2Element;
  };
  interface HTMLElementTagNameMap {
    'rs-button2': HTMLRsButton2Element;
  }
}

declare namespace LocalJSX {
  interface RsButton2 extends JSXBase.HTMLAttributes<HTMLRsButton2Element> {}

  interface IntrinsicElements {
    'rs-button2': RsButton2;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


