/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RsButton {
    'activateRipple': () => Promise<void>;
    'disabled': boolean;
    'exited': boolean;
    'isDisabled': () => Promise<void>;
    'isExited': () => Promise<void>;
  }
}

declare global {


  interface HTMLRsButtonElement extends Components.RsButton, HTMLStencilElement {}
  var HTMLRsButtonElement: {
    prototype: HTMLRsButtonElement;
    new (): HTMLRsButtonElement;
  };
  interface HTMLElementTagNameMap {
    'rs-button': HTMLRsButtonElement;
  }
}

declare namespace LocalJSX {
  interface RsButton extends JSXBase.HTMLAttributes<HTMLRsButtonElement> {
    'disabled'?: boolean;
    'exited'?: boolean;
  }

  interface IntrinsicElements {
    'rs-button': RsButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


