/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RsSlider {}
}

declare global {


  interface HTMLRsSliderElement extends Components.RsSlider, HTMLStencilElement {}
  var HTMLRsSliderElement: {
    prototype: HTMLRsSliderElement;
    new (): HTMLRsSliderElement;
  };
  interface HTMLElementTagNameMap {
    'rs-slider': HTMLRsSliderElement;
  }
}

declare namespace LocalJSX {
  interface RsSlider extends JSXBase.HTMLAttributes<HTMLRsSliderElement> {}

  interface IntrinsicElements {
    'rs-slider': RsSlider;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


