/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RsSnackbar {
    'first': string;
    'last': string;
    'middle': string;
  }
}

declare global {


  interface HTMLRsSnackbarElement extends Components.RsSnackbar, HTMLStencilElement {}
  var HTMLRsSnackbarElement: {
    prototype: HTMLRsSnackbarElement;
    new (): HTMLRsSnackbarElement;
  };
  interface HTMLElementTagNameMap {
    'rs-snackbar': HTMLRsSnackbarElement;
  }
}

declare namespace LocalJSX {
  interface RsSnackbar extends JSXBase.HTMLAttributes<HTMLRsSnackbarElement> {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }

  interface IntrinsicElements {
    'rs-snackbar': RsSnackbar;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


