/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RsDataTable {
    'fixed': boolean;
    'isFixed': () => Promise<void>;
  }
  interface RsDataTableBody {
    'isCheckboxChecked': (checkbox: any, row: any) => Promise<void>;
  }
  interface RsDataTableCell {}
  interface RsDataTableHeader {}
  interface RsDataTableRow {}
}

declare global {


  interface HTMLRsDataTableElement extends Components.RsDataTable, HTMLStencilElement {}
  var HTMLRsDataTableElement: {
    prototype: HTMLRsDataTableElement;
    new (): HTMLRsDataTableElement;
  };

  interface HTMLRsDataTableBodyElement extends Components.RsDataTableBody, HTMLStencilElement {}
  var HTMLRsDataTableBodyElement: {
    prototype: HTMLRsDataTableBodyElement;
    new (): HTMLRsDataTableBodyElement;
  };

  interface HTMLRsDataTableCellElement extends Components.RsDataTableCell, HTMLStencilElement {}
  var HTMLRsDataTableCellElement: {
    prototype: HTMLRsDataTableCellElement;
    new (): HTMLRsDataTableCellElement;
  };

  interface HTMLRsDataTableHeaderElement extends Components.RsDataTableHeader, HTMLStencilElement {}
  var HTMLRsDataTableHeaderElement: {
    prototype: HTMLRsDataTableHeaderElement;
    new (): HTMLRsDataTableHeaderElement;
  };

  interface HTMLRsDataTableRowElement extends Components.RsDataTableRow, HTMLStencilElement {}
  var HTMLRsDataTableRowElement: {
    prototype: HTMLRsDataTableRowElement;
    new (): HTMLRsDataTableRowElement;
  };
  interface HTMLElementTagNameMap {
    'rs-data-table': HTMLRsDataTableElement;
    'rs-data-table-body': HTMLRsDataTableBodyElement;
    'rs-data-table-cell': HTMLRsDataTableCellElement;
    'rs-data-table-header': HTMLRsDataTableHeaderElement;
    'rs-data-table-row': HTMLRsDataTableRowElement;
  }
}

declare namespace LocalJSX {
  interface RsDataTable extends JSXBase.HTMLAttributes<HTMLRsDataTableElement> {
    'fixed'?: boolean;
  }
  interface RsDataTableBody extends JSXBase.HTMLAttributes<HTMLRsDataTableBodyElement> {}
  interface RsDataTableCell extends JSXBase.HTMLAttributes<HTMLRsDataTableCellElement> {}
  interface RsDataTableHeader extends JSXBase.HTMLAttributes<HTMLRsDataTableHeaderElement> {}
  interface RsDataTableRow extends JSXBase.HTMLAttributes<HTMLRsDataTableRowElement> {}

  interface IntrinsicElements {
    'rs-data-table': RsDataTable;
    'rs-data-table-body': RsDataTableBody;
    'rs-data-table-cell': RsDataTableCell;
    'rs-data-table-header': RsDataTableHeader;
    'rs-data-table-row': RsDataTableRow;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


