/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RsMenu {
    'isOpened': () => Promise<void>;
    'opened': boolean;
  }
}

declare global {


  interface HTMLRsMenuElement extends Components.RsMenu, HTMLStencilElement {}
  var HTMLRsMenuElement: {
    prototype: HTMLRsMenuElement;
    new (): HTMLRsMenuElement;
  };
  interface HTMLElementTagNameMap {
    'rs-menu': HTMLRsMenuElement;
  }
}

declare namespace LocalJSX {
  interface RsMenu extends JSXBase.HTMLAttributes<HTMLRsMenuElement> {
    'onChange'?: (event: CustomEvent<any>) => void;
    'opened'?: boolean;
  }

  interface IntrinsicElements {
    'rs-menu': RsMenu;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


