/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RsDialog {}
}

declare global {


  interface HTMLRsDialogElement extends Components.RsDialog, HTMLStencilElement {}
  var HTMLRsDialogElement: {
    prototype: HTMLRsDialogElement;
    new (): HTMLRsDialogElement;
  };
  interface HTMLElementTagNameMap {
    'rs-dialog': HTMLRsDialogElement;
  }
}

declare namespace LocalJSX {
  interface RsDialog extends JSXBase.HTMLAttributes<HTMLRsDialogElement> {}

  interface IntrinsicElements {
    'rs-dialog': RsDialog;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


