/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RsCheckbox {}
}

declare global {


  interface HTMLRsCheckboxElement extends Components.RsCheckbox, HTMLStencilElement {}
  var HTMLRsCheckboxElement: {
    prototype: HTMLRsCheckboxElement;
    new (): HTMLRsCheckboxElement;
  };
  interface HTMLElementTagNameMap {
    'rs-checkbox': HTMLRsCheckboxElement;
  }
}

declare namespace LocalJSX {
  interface RsCheckbox extends JSXBase.HTMLAttributes<HTMLRsCheckboxElement> {}

  interface IntrinsicElements {
    'rs-checkbox': RsCheckbox;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


