/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Element,
} from '@stencil/core';


export namespace Components {
  interface RsRadio {
    'activateRipple': () => Promise<void>;
    'checkDataChecked': () => Promise<void>;
    'checked': boolean;
    'dataChecked': string;
    'disabled': boolean;
    'extractSameGroupRadios': () => Promise<Element[]>;
    'id': string;
    'isChecked': () => Promise<void>;
    'isDataChecked': () => Promise<void>;
    'isDisabled': () => Promise<void>;
    'label': string;
    'name': string;
    'uncheckSameGroupRadios': () => Promise<void>;
    'value': string;
  }
}

declare global {


  interface HTMLRsRadioElement extends Components.RsRadio, HTMLStencilElement {}
  var HTMLRsRadioElement: {
    prototype: HTMLRsRadioElement;
    new (): HTMLRsRadioElement;
  };
  interface HTMLElementTagNameMap {
    'rs-radio': HTMLRsRadioElement;
  }
}

declare namespace LocalJSX {
  interface RsRadio extends JSXBase.HTMLAttributes<HTMLRsRadioElement> {
    'checked'?: boolean;
    'dataChecked'?: string;
    'disabled'?: boolean;
    'id'?: string;
    'label'?: string;
    'name'?: string;
    'onChange'?: (event: CustomEvent<any>) => void;
    'value'?: string;
  }

  interface IntrinsicElements {
    'rs-radio': RsRadio;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


