/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RsRadio {
    'checked': boolean;
    'dataChecked': string;
    'disabled': boolean;
    'id': string;
    'isChecked': () => Promise<void>;
    'isDisabled': () => Promise<void>;
    'isHostChecked': () => Promise<void>;
    'label': string;
    'updateDataChecked': () => Promise<void>;
  }
}

declare global {


  interface HTMLRsRadioElement extends Components.RsRadio, HTMLStencilElement {}
  var HTMLRsRadioElement: {
    prototype: HTMLRsRadioElement;
    new (): HTMLRsRadioElement;
  };
  interface HTMLElementTagNameMap {
    'rs-radio': HTMLRsRadioElement;
  }
}

declare namespace LocalJSX {
  interface RsRadio extends JSXBase.HTMLAttributes<HTMLRsRadioElement> {
    'checked'?: boolean;
    'dataChecked'?: string;
    'disabled'?: boolean;
    'id'?: string;
    'label'?: string;
  }

  interface IntrinsicElements {
    'rs-radio': RsRadio;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


