/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RsChip {
    'activateRipple': () => Promise<void>;
    'isSelected': () => Promise<void>;
    'isShaped': () => Promise<void>;
    'selected': boolean;
    'shaped': boolean;
  }
}

declare global {


  interface HTMLRsChipElement extends Components.RsChip, HTMLStencilElement {}
  var HTMLRsChipElement: {
    prototype: HTMLRsChipElement;
    new (): HTMLRsChipElement;
  };
  interface HTMLElementTagNameMap {
    'rs-chip': HTMLRsChipElement;
  }
}

declare namespace LocalJSX {
  interface RsChip extends JSXBase.HTMLAttributes<HTMLRsChipElement> {
    'selected'?: boolean;
    'shaped'?: boolean;
  }

  interface IntrinsicElements {
    'rs-chip': RsChip;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


