/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RsTextarea {
    'addFocusStyle': () => Promise<void>;
    'changeHandler': () => Promise<void>;
    'countable': boolean;
    'disabled': boolean;
    'floatLabel': () => Promise<void>;
    'invalid': boolean;
    'isCountable': () => Promise<void>;
    'isDisabled': () => Promise<void>;
    'isInvalid': () => Promise<void>;
    'isRequired': () => Promise<void>;
    'label': string;
    'maxlength': string;
    'placeholder': string;
    'removeFocusStyle': () => Promise<void>;
    'required': boolean;
    'retriveLabelWidth': (labels: any) => Promise<any>;
    'setLabelWidthToNotch': () => Promise<void>;
    'type': string;
    'value': string;
  }
  interface RsTextfield {
    'addFocusStyle': () => Promise<void>;
    'changeHandler': () => Promise<void>;
    'countable': boolean;
    'disabled': boolean;
    'floatLabel': () => Promise<void>;
    'invalid': boolean;
    'isCountable': () => Promise<void>;
    'isDisabled': () => Promise<void>;
    'isInvalid': () => Promise<void>;
    'isRequired': () => Promise<void>;
    'label': string;
    'maxlength': string;
    'placeholder': string;
    'removeFocusStyle': () => Promise<void>;
    'required': boolean;
    'retriveLabelWidth': (labels: any) => Promise<any>;
    'setLabelWidthToNotch': () => Promise<void>;
    'type': string;
    'value': string;
  }
}

declare global {


  interface HTMLRsTextareaElement extends Components.RsTextarea, HTMLStencilElement {}
  var HTMLRsTextareaElement: {
    prototype: HTMLRsTextareaElement;
    new (): HTMLRsTextareaElement;
  };

  interface HTMLRsTextfieldElement extends Components.RsTextfield, HTMLStencilElement {}
  var HTMLRsTextfieldElement: {
    prototype: HTMLRsTextfieldElement;
    new (): HTMLRsTextfieldElement;
  };
  interface HTMLElementTagNameMap {
    'rs-textarea': HTMLRsTextareaElement;
    'rs-textfield': HTMLRsTextfieldElement;
  }
}

declare namespace LocalJSX {
  interface RsTextarea extends JSXBase.HTMLAttributes<HTMLRsTextareaElement> {
    'countable'?: boolean;
    'disabled'?: boolean;
    'invalid'?: boolean;
    'label'?: string;
    'maxlength'?: string;
    'onChange'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string;
    'required'?: boolean;
    'type'?: string;
    'value'?: string;
  }
  interface RsTextfield extends JSXBase.HTMLAttributes<HTMLRsTextfieldElement> {
    'countable'?: boolean;
    'disabled'?: boolean;
    'invalid'?: boolean;
    'label'?: string;
    'maxlength'?: string;
    'onChange'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string;
    'required'?: boolean;
    'type'?: string;
    'value'?: string;
  }

  interface IntrinsicElements {
    'rs-textarea': RsTextarea;
    'rs-textfield': RsTextfield;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


