/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RsList {}
  interface RsListDivider {}
  interface RsListGraphic {}
  interface RsListGroup {}
  interface RsListItem {
    'activated': boolean;
    'disabled': boolean;
    'isActivated': () => Promise<void>;
    'isDisabled': () => Promise<void>;
    'isSelected': () => Promise<void>;
    'selected': boolean;
  }
  interface RsListMeta {}
  interface RsListPrimary {}
  interface RsListSecondary {}
  interface RsListSubheader {}
  interface RsListText {}
}

declare global {


  interface HTMLRsListElement extends Components.RsList, HTMLStencilElement {}
  var HTMLRsListElement: {
    prototype: HTMLRsListElement;
    new (): HTMLRsListElement;
  };

  interface HTMLRsListDividerElement extends Components.RsListDivider, HTMLStencilElement {}
  var HTMLRsListDividerElement: {
    prototype: HTMLRsListDividerElement;
    new (): HTMLRsListDividerElement;
  };

  interface HTMLRsListGraphicElement extends Components.RsListGraphic, HTMLStencilElement {}
  var HTMLRsListGraphicElement: {
    prototype: HTMLRsListGraphicElement;
    new (): HTMLRsListGraphicElement;
  };

  interface HTMLRsListGroupElement extends Components.RsListGroup, HTMLStencilElement {}
  var HTMLRsListGroupElement: {
    prototype: HTMLRsListGroupElement;
    new (): HTMLRsListGroupElement;
  };

  interface HTMLRsListItemElement extends Components.RsListItem, HTMLStencilElement {}
  var HTMLRsListItemElement: {
    prototype: HTMLRsListItemElement;
    new (): HTMLRsListItemElement;
  };

  interface HTMLRsListMetaElement extends Components.RsListMeta, HTMLStencilElement {}
  var HTMLRsListMetaElement: {
    prototype: HTMLRsListMetaElement;
    new (): HTMLRsListMetaElement;
  };

  interface HTMLRsListPrimaryElement extends Components.RsListPrimary, HTMLStencilElement {}
  var HTMLRsListPrimaryElement: {
    prototype: HTMLRsListPrimaryElement;
    new (): HTMLRsListPrimaryElement;
  };

  interface HTMLRsListSecondaryElement extends Components.RsListSecondary, HTMLStencilElement {}
  var HTMLRsListSecondaryElement: {
    prototype: HTMLRsListSecondaryElement;
    new (): HTMLRsListSecondaryElement;
  };

  interface HTMLRsListSubheaderElement extends Components.RsListSubheader, HTMLStencilElement {}
  var HTMLRsListSubheaderElement: {
    prototype: HTMLRsListSubheaderElement;
    new (): HTMLRsListSubheaderElement;
  };

  interface HTMLRsListTextElement extends Components.RsListText, HTMLStencilElement {}
  var HTMLRsListTextElement: {
    prototype: HTMLRsListTextElement;
    new (): HTMLRsListTextElement;
  };
  interface HTMLElementTagNameMap {
    'rs-list': HTMLRsListElement;
    'rs-list-divider': HTMLRsListDividerElement;
    'rs-list-graphic': HTMLRsListGraphicElement;
    'rs-list-group': HTMLRsListGroupElement;
    'rs-list-item': HTMLRsListItemElement;
    'rs-list-meta': HTMLRsListMetaElement;
    'rs-list-primary': HTMLRsListPrimaryElement;
    'rs-list-secondary': HTMLRsListSecondaryElement;
    'rs-list-subheader': HTMLRsListSubheaderElement;
    'rs-list-text': HTMLRsListTextElement;
  }
}

declare namespace LocalJSX {
  interface RsList extends JSXBase.HTMLAttributes<HTMLRsListElement> {}
  interface RsListDivider extends JSXBase.HTMLAttributes<HTMLRsListDividerElement> {}
  interface RsListGraphic extends JSXBase.HTMLAttributes<HTMLRsListGraphicElement> {}
  interface RsListGroup extends JSXBase.HTMLAttributes<HTMLRsListGroupElement> {}
  interface RsListItem extends JSXBase.HTMLAttributes<HTMLRsListItemElement> {
    'activated'?: boolean;
    'disabled'?: boolean;
    'selected'?: boolean;
  }
  interface RsListMeta extends JSXBase.HTMLAttributes<HTMLRsListMetaElement> {}
  interface RsListPrimary extends JSXBase.HTMLAttributes<HTMLRsListPrimaryElement> {}
  interface RsListSecondary extends JSXBase.HTMLAttributes<HTMLRsListSecondaryElement> {}
  interface RsListSubheader extends JSXBase.HTMLAttributes<HTMLRsListSubheaderElement> {}
  interface RsListText extends JSXBase.HTMLAttributes<HTMLRsListTextElement> {}

  interface IntrinsicElements {
    'rs-list': RsList;
    'rs-list-divider': RsListDivider;
    'rs-list-graphic': RsListGraphic;
    'rs-list-group': RsListGroup;
    'rs-list-item': RsListItem;
    'rs-list-meta': RsListMeta;
    'rs-list-primary': RsListPrimary;
    'rs-list-secondary': RsListSecondary;
    'rs-list-subheader': RsListSubheader;
    'rs-list-text': RsListText;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


