/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RsCheckbox {
    'activateRipple': () => Promise<void>;
    'checked': boolean;
    'disabled': boolean;
    'id': string;
    'indeterminate': boolean;
    'isChecked': () => Promise<void>;
    'isDisabled': () => Promise<void>;
    'isHostChecked': () => Promise<void>;
    'isHostIndeterminate': () => Promise<void>;
    'isIndeterminate': () => Promise<void>;
    'label': string;
    'name': string;
    'updateDataChecked': () => Promise<void>;
    'value': string | number;
  }
}

declare global {


  interface HTMLRsCheckboxElement extends Components.RsCheckbox, HTMLStencilElement {}
  var HTMLRsCheckboxElement: {
    prototype: HTMLRsCheckboxElement;
    new (): HTMLRsCheckboxElement;
  };
  interface HTMLElementTagNameMap {
    'rs-checkbox': HTMLRsCheckboxElement;
  }
}

declare namespace LocalJSX {
  interface RsCheckbox extends JSXBase.HTMLAttributes<HTMLRsCheckboxElement> {
    'checked'?: boolean;
    'disabled'?: boolean;
    'id'?: string;
    'indeterminate'?: boolean;
    'label'?: string;
    'name'?: string;
    'onChange'?: (event: CustomEvent<any>) => void;
    'value'?: string | number;
  }

  interface IntrinsicElements {
    'rs-checkbox': RsCheckbox;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


