/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RsAppLayout {}
  interface RsAppLayoutContent {}
}

declare global {


  interface HTMLRsAppLayoutElement extends Components.RsAppLayout, HTMLStencilElement {}
  var HTMLRsAppLayoutElement: {
    prototype: HTMLRsAppLayoutElement;
    new (): HTMLRsAppLayoutElement;
  };

  interface HTMLRsAppLayoutContentElement extends Components.RsAppLayoutContent, HTMLStencilElement {}
  var HTMLRsAppLayoutContentElement: {
    prototype: HTMLRsAppLayoutContentElement;
    new (): HTMLRsAppLayoutContentElement;
  };
  interface HTMLElementTagNameMap {
    'rs-app-layout': HTMLRsAppLayoutElement;
    'rs-app-layout-content': HTMLRsAppLayoutContentElement;
  }
}

declare namespace LocalJSX {
  interface RsAppLayout extends JSXBase.HTMLAttributes<HTMLRsAppLayoutElement> {}
  interface RsAppLayoutContent extends JSXBase.HTMLAttributes<HTMLRsAppLayoutContentElement> {}

  interface IntrinsicElements {
    'rs-app-layout': RsAppLayout;
    'rs-app-layout-content': RsAppLayoutContent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


