/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RsAppBar {
    'compactable': boolean;
    'fixed': boolean;
    'isCompactable': () => Promise<void>;
    'isFixed': () => Promise<void>;
    'updateAppBarWidth': () => Promise<void>;
  }
  interface RsAppBarItem {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface RsAppBarNav {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface RsAppBarTitle {}
  interface RsAppBarTool {
    'first': string;
    'last': string;
    'middle': string;
  }
}

declare global {


  interface HTMLRsAppBarElement extends Components.RsAppBar, HTMLStencilElement {}
  var HTMLRsAppBarElement: {
    prototype: HTMLRsAppBarElement;
    new (): HTMLRsAppBarElement;
  };

  interface HTMLRsAppBarItemElement extends Components.RsAppBarItem, HTMLStencilElement {}
  var HTMLRsAppBarItemElement: {
    prototype: HTMLRsAppBarItemElement;
    new (): HTMLRsAppBarItemElement;
  };

  interface HTMLRsAppBarNavElement extends Components.RsAppBarNav, HTMLStencilElement {}
  var HTMLRsAppBarNavElement: {
    prototype: HTMLRsAppBarNavElement;
    new (): HTMLRsAppBarNavElement;
  };

  interface HTMLRsAppBarTitleElement extends Components.RsAppBarTitle, HTMLStencilElement {}
  var HTMLRsAppBarTitleElement: {
    prototype: HTMLRsAppBarTitleElement;
    new (): HTMLRsAppBarTitleElement;
  };

  interface HTMLRsAppBarToolElement extends Components.RsAppBarTool, HTMLStencilElement {}
  var HTMLRsAppBarToolElement: {
    prototype: HTMLRsAppBarToolElement;
    new (): HTMLRsAppBarToolElement;
  };
  interface HTMLElementTagNameMap {
    'rs-app-bar': HTMLRsAppBarElement;
    'rs-app-bar-item': HTMLRsAppBarItemElement;
    'rs-app-bar-nav': HTMLRsAppBarNavElement;
    'rs-app-bar-title': HTMLRsAppBarTitleElement;
    'rs-app-bar-tool': HTMLRsAppBarToolElement;
  }
}

declare namespace LocalJSX {
  interface RsAppBar extends JSXBase.HTMLAttributes<HTMLRsAppBarElement> {
    'compactable'?: boolean;
    'fixed'?: boolean;
  }
  interface RsAppBarItem extends JSXBase.HTMLAttributes<HTMLRsAppBarItemElement> {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }
  interface RsAppBarNav extends JSXBase.HTMLAttributes<HTMLRsAppBarNavElement> {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }
  interface RsAppBarTitle extends JSXBase.HTMLAttributes<HTMLRsAppBarTitleElement> {}
  interface RsAppBarTool extends JSXBase.HTMLAttributes<HTMLRsAppBarToolElement> {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }

  interface IntrinsicElements {
    'rs-app-bar': RsAppBar;
    'rs-app-bar-item': RsAppBarItem;
    'rs-app-bar-nav': RsAppBarNav;
    'rs-app-bar-title': RsAppBarTitle;
    'rs-app-bar-tool': RsAppBarTool;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


