/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RsAppBar {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface RsAppBarNav {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface RsAppBarTitle {
    'first': string;
    'last': string;
    'middle': string;
  }
}

declare global {


  interface HTMLRsAppBarElement extends Components.RsAppBar, HTMLStencilElement {}
  var HTMLRsAppBarElement: {
    prototype: HTMLRsAppBarElement;
    new (): HTMLRsAppBarElement;
  };

  interface HTMLRsAppBarNavElement extends Components.RsAppBarNav, HTMLStencilElement {}
  var HTMLRsAppBarNavElement: {
    prototype: HTMLRsAppBarNavElement;
    new (): HTMLRsAppBarNavElement;
  };

  interface HTMLRsAppBarTitleElement extends Components.RsAppBarTitle, HTMLStencilElement {}
  var HTMLRsAppBarTitleElement: {
    prototype: HTMLRsAppBarTitleElement;
    new (): HTMLRsAppBarTitleElement;
  };
  interface HTMLElementTagNameMap {
    'rs-app-bar': HTMLRsAppBarElement;
    'rs-app-bar-nav': HTMLRsAppBarNavElement;
    'rs-app-bar-title': HTMLRsAppBarTitleElement;
  }
}

declare namespace LocalJSX {
  interface RsAppBar extends JSXBase.HTMLAttributes<HTMLRsAppBarElement> {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }
  interface RsAppBarNav extends JSXBase.HTMLAttributes<HTMLRsAppBarNavElement> {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }
  interface RsAppBarTitle extends JSXBase.HTMLAttributes<HTMLRsAppBarTitleElement> {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }

  interface IntrinsicElements {
    'rs-app-bar': RsAppBar;
    'rs-app-bar-nav': RsAppBarNav;
    'rs-app-bar-title': RsAppBarTitle;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


