/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppBar {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLAppBarElement extends Components.AppBar, HTMLStencilElement {}
  var HTMLAppBarElement: {
    prototype: HTMLAppBarElement;
    new (): HTMLAppBarElement;
  };
  interface HTMLElementTagNameMap {
    'app-bar': HTMLAppBarElement;
  }
}

declare namespace LocalJSX {
  interface AppBar extends JSXBase.HTMLAttributes<HTMLAppBarElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'app-bar': AppBar;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


