/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RsDrawer {
    'closeDrawerMotion': () => Promise<void>;
    'openDrawerMotion': () => Promise<void>;
    'opened': boolean;
  }
}

declare global {


  interface HTMLRsDrawerElement extends Components.RsDrawer, HTMLStencilElement {}
  var HTMLRsDrawerElement: {
    prototype: HTMLRsDrawerElement;
    new (): HTMLRsDrawerElement;
  };
  interface HTMLElementTagNameMap {
    'rs-drawer': HTMLRsDrawerElement;
  }
}

declare namespace LocalJSX {
  interface RsDrawer extends JSXBase.HTMLAttributes<HTMLRsDrawerElement> {
    'onChange'?: (event: CustomEvent<any>) => void;
    'opened'?: boolean;
  }

  interface IntrinsicElements {
    'rs-drawer': RsDrawer;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


