/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RsImageList {}
}

declare global {


  interface HTMLRsImageListElement extends Components.RsImageList, HTMLStencilElement {}
  var HTMLRsImageListElement: {
    prototype: HTMLRsImageListElement;
    new (): HTMLRsImageListElement;
  };
  interface HTMLElementTagNameMap {
    'rs-image-list': HTMLRsImageListElement;
  }
}

declare namespace LocalJSX {
  interface RsImageList extends JSXBase.HTMLAttributes<HTMLRsImageListElement> {}

  interface IntrinsicElements {
    'rs-image-list': RsImageList;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


