/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RsAppLayout {}
}

declare global {


  interface HTMLRsAppLayoutElement extends Components.RsAppLayout, HTMLStencilElement {}
  var HTMLRsAppLayoutElement: {
    prototype: HTMLRsAppLayoutElement;
    new (): HTMLRsAppLayoutElement;
  };
  interface HTMLElementTagNameMap {
    'rs-app-layout': HTMLRsAppLayoutElement;
  }
}

declare namespace LocalJSX {
  interface RsAppLayout extends JSXBase.HTMLAttributes<HTMLRsAppLayoutElement> {}

  interface IntrinsicElements {
    'rs-app-layout': RsAppLayout;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


